export const SHOW_NEXT_COORDS = 'SHOW_NEXT_COORDS';
export type SHOW_NEXT_COORDS = typeof SHOW_NEXT_COORDS;

export const HANDLE_SQUARE_CLICKED = 'HANDLE_SQUARE_CLICKED';
export type HANDLE_SQUARE_CLICKED = typeof HANDLE_SQUARE_CLICKED;

export const START_ROUND = 'START_ROUND';
export type START_ROUND = typeof START_ROUND;

export const SET_COUNTDOWN_VALUE = 'SET_COUNTDOWN_VALUE';
export type SET_COUNTDOWN_VALUE = typeof SET_COUNTDOWN_VALUE;

export const START_PLAY = 'START_PLAY';
export type START_PLAY = typeof START_PLAY;
