export const HANDLE_CORRECT_SQUARE_CLICKED = 'HANDLE_CORRECT_SQUARE_CLICKED';
export type HANDLE_CORRECT_SQUARE_CLICKED = typeof HANDLE_CORRECT_SQUARE_CLICKED;

export const HANDLE_INCORRECT_SQUARE_CLICKED = 'HANDLE_INCORRECT_SQUARE_CLICKED';
export type HANDLE_INCORRECT_SQUARE_CLICKED = typeof HANDLE_INCORRECT_SQUARE_CLICKED;

export const DONE_SHOWING_PENALTY = 'DONE_SHOWING_PENALTY';
export type DONE_SHOWING_PENALTY = typeof DONE_SHOWING_PENALTY;

export const START_ROUND = 'START_ROUND';
export type START_ROUND = typeof START_ROUND;

export const SET_COUNTDOWN_VALUE = 'SET_COUNTDOWN_VALUE';
export type SET_COUNTDOWN_VALUE = typeof SET_COUNTDOWN_VALUE;

export const START_PLAY = 'START_PLAY';
export type START_PLAY = typeof START_PLAY;

export const SET_ROUND_TIMER_VALUE = 'SET_ROUND_TIMER_VALUE';
export type SET_ROUND_TIMER_VALUE = typeof SET_ROUND_TIMER_VALUE;

export const DECREMENT_ROUND_TIMER_VALUE = 'DECREMENT_ROUND_TIMER_VALUE';
export type DECREMENT_ROUND_TIMER_VALUE = typeof DECREMENT_ROUND_TIMER_VALUE;

export const END_ROUND = 'END_ROUND';
export type END_ROUND = typeof END_ROUND;

export const RESET_COUNT = 'RESET_COUNT';
export type RESET_COUNT = typeof RESET_COUNT;

export const TOGGLE_BOARD_DIRECTION = 'TOGGLE_BOARD_DIRECTION';
export type TOGGLE_BOARD_DIRECTION = typeof TOGGLE_BOARD_DIRECTION;
